<?php

/**
 * ContractProductRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContractProductRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ContractProductRelationTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContractProductRelation');
    }
}