<?php

/**
 * InvoiceTaxRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvoiceTaxRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return InvoiceTaxRelationTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InvoiceTaxRelation');
    }
}