<?php

/**
 * ProductTaxRelationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductTaxRelationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return ProductTaxRelationTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductTaxRelation');
    }
}